homework-1
Kaisar283/Hotel pull request #1
Opened 2024-11-03 18:37 UTC by Kaisar283

2024-11-03 19:50 UTC, Alexmansar requested changes
@Kaisar283 Hi)) I have same comments))please fix it)))

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/Repository/ApartmentStorage.java
> +package Repository;
in general - package names in uppercase
just repository 
the same for other packages

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/Repository/ApartmentStorage.java
> +
I would returnb here list as well

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/console/UserConsole.java
> +        System.out.println("Type 'help' for a list of commands.");
you can use text bloks here 
https://www.baeldung.com/java-text-blocks

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/console/UserConsole.java
> +        if (commandParts.length < 2){
what is 2? create a constant and give names for such vars, please))

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/console/UserConsole.java
> +            pageSize = Integer.parseInt(commandParts[2]);
same here

2024-11-03 19:50 UTC, Alexmansar commented on src/main/java/console/UserConsole.java
> +        if(commandParts.length >= 5){
and here :)

2024-11-04 04:03 UTC, Kaisar283 commented
@Alexmansar Hi.
Your review hepled improve my code, thanks.
I fixed your remaks, please check)

2024-11-04 07:43 UTC, Alexmansar approved these changes
@Kaisar283 you can merge it))

2024-11-04 08:13 UTC, merged