Homework 2
Kaisar283/Hotel pull request #2
Opened 2024-11-06 18:44 UTC by Kaisar283

@Alexmansar Hi
I finished the second homework, please check)

2024-11-07 10:07 UTC, Alexmansar requested changes
@Kaisar283 Hi)) Good job in general. But i have some comments, please chech it

2024-11-07 10:07 UTC, Alexmansar commented on .github/workflows/ci.yaml
> +        run: mvn -B package --file pom.xml
what about jar file?

2024-11-07 10:07 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/console/UserConsole.java
> +    private void releaseApartment(String @NotNull [] commandParts){
@NotNull String [] commandParts?

2024-11-07 10:07 UTC, Alexmansar commented on src/test/java/kz/andersen/java_intensive_13/console/UserConsoleTest.java
> +    }
make it orivate, and move after all tests

2024-11-07 10:07 UTC, Alexmansar commented on src/test/java/kz/andersen/java_intensive_13/console/UserConsoleTest.java
> +    public void testRegisterApartment() {
remove prefix test from methids. in each case please

2024-11-07 10:07 UTC, Alexmansar commented on src/test/java/kz/andersen/java_intensive_13/services/ApartmentServiceTest.java
> +    @Mock
InjectMocks ?

2024-11-07 10:07 UTC, Alexmansar commented on src/test/java/kz/andersen/java_intensive_13/services/ApartmentServiceTest.java
> +    }
I think you can remove it. try please

2024-11-07 14:12 UTC, Kaisar283 commented on src/test/java/kz/andersen/java_intensive_13/services/ApartmentServiceTest.java
> +    @Mock
I just noticed that ApartmentServiceTest do not use the ApartmentStorage class. If I use @InjectMocks annotaion to ApartmentService, all test faild. I checked with Debug, then a see all this functinality not use ApartmentStorage class. Is always null. I don't know what shold I do. Please help.
<img width="959" alt="Снимок экрана 2024-11-07 191147" src="https://github.com/user-attachments/assets/1c8b7023-2571-4821-aa9c-25da81c98405">

2024-11-07 16:24 UTC, Alexmansar commented on src/test/java/kz/andersen/java_intensive_13/services/ApartmentServiceTest.java
> +    @Mock
try add Spy)

but in general your tests looks strange

example
![image](https://github.com/user-attachments/assets/2ea0d212-2c50-4d30-9aae-c138711d8cae)

you shoud use given, when with mocks.. not with tagret class

storage is bull - because you shoul stub it in when(..)f.e.

about verify - the same - verify mocks, not target))

2024-11-08 06:27 UTC, Kaisar283 commented
@Alexmansar Hi
I rewrote the tests using mock object and modified github workfolw file to generate artifact. Please check.

2024-11-08 09:40 UTC, Alexmansar approved these changes
@Kaisar283 pleasew, fix small comment and merge

2024-11-08 09:40 UTC, Alexmansar commented on pom.xml
> +                            </manifest>
remove this comment

2024-11-08 09:46 UTC, merged