Data base
Kaisar283/Hotel pull request #6
Opened 2024-11-19 08:10 UTC by Kaisar283

@Alexmansar Hi
I've done the task, please check

2024-11-19 12:04 UTC, Alexmansar requested changes
@Kaisar283 Hi) I have some general comments, so please fix it in each case)

2024-11-19 12:04 UTC, Alexmansar commented on .github/workflows/ci.yaml
> +      - name: Build the project (without tests)
why we skip tests?

2024-11-19 12:04 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/models/User.java
> +    UserRole userRole;
what about access modifier?

2024-11-19 12:04 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """;
use queries as a constants on the class level

2024-11-19 12:04 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """, apartment.getId() );
all in general

2024-11-19 12:04 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/UserRepository.java
> +        ZonedDateTime updatedAt = ZonedDateTime.now(ZoneId.systemDefault());
you ca use it directly in lines 53-58

2024-11-19 12:04 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/db_config/DataSource.java
> +        config.setPassword( "admin" );
can we read it from file?

2024-11-19 12:45 UTC, Kaisar283 commented on .github/workflows/ci.yaml
> +      - name: Build the project (without tests)
All tests are run after migration to the database. Liquibase does not migrate to the database when building the project. So I separate test phase. Tests are run with DB connection

2024-11-19 13:25 UTC, Alexmansar commented on .github/workflows/ci.yaml
> +      - name: Build the project (without tests)
ok)

2024-11-19 13:33 UTC, Kaisar283 commented
@Alexmansar please check

2024-11-19 14:10 UTC, Alexmansar requested changes

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +        String SQLQuery = "SELECT * FROM apartment LEFT JOIN public.user ON apartment.\"reservedBy\" = public.user.id;";
and this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """, apartmentId);
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """;
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """;
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """;
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +                """;
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/UserRepository.java
> +                """, userId);
this

2024-11-19 14:10 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/UserRepository.java
> +                """;
this

2024-11-19 18:25 UTC, Kaisar283 commented
@Alexmansar please check

2024-11-20 07:44 UTC, Alexmansar approved these changes
@Kaisar283 Please, fix small remarks and merge

2024-11-20 07:44 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/UserRepository.java
> +    private final String INSET_USER_QUERY = """
INSERT

2024-11-20 07:44 UTC, Alexmansar commented on src/main/java/kz/andersen/java_intensive_13/repository/ApartmentStorage.java
> +    private final String INSET_APARTMENT_QUERY = """
same

2024-11-20 08:17 UTC, merged